# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - "-SA1029"
  exclusions:
    rules:
      - text: 'Error return value of `(logger.Sync|ni.AddEventHandler|config.BindEnv)` is not checked'
        linters:
          - errcheck
