---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mechanic-win2019
  namespace: mechanic
spec:
  selector:
    matchLabels:
      app: mechanic
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mechanic
    spec:
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
        kubernetes.io/os-sku: Windows2019
      serviceAccountName: mechanic
      hostPID: true # Facilitates entering the host mount namespace via init
      containers:
      - name: mechanic
        image: ghcr.io/amargherio/mechanic:v2025.10-windows2019
        imagePullPolicy: Always
        securityContext:
          privileged: true # Gives permission to nsenter /proc/1/ns/mnt
          readOnlyRootFilesystem: true
        env:
        - name: MECHANIC_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 25Mi
        volumeMounts:
          - name: config
            mountPath: /etc/mechanic
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: mechanic
