apiVersion: v1
kind: ServiceAccount
metadata:
  name: mechanic
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mechanic
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  selector:
    matchLabels:
      app: mechanic
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mechanic
    spec:
      serviceAccountName: mechanic
      hostPID: true # Facilitates entering the host mount namespace via init
      containers:
      - name: mechanic
        image: mechanic:1.0.0
        imagePullPolicy: Always
        securityContext:
          privileged: true # Gives permission to nsenter /proc/1/ns/mnt
          readOnlyRootFilesystem: true
        env:
        - name: MECHANIC_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
