apiVersion: v1
kind: ServiceAccount
metadata:
  name: mechanic
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mechanic-cr
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mechanic-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mechanic-cr
subjects:
  - kind: ServiceAccount
    name: mechanic
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mechanic
  namespace: default
spec:
  selector:
    matchLabels:
      app: mechanic
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mechanic
    spec:
      serviceAccountName: mechanic
      hostPID: true # Facilitates entering the host mount namespace via init
      containers:
      - name: mechanic
        image: amargheriocss.azurecr.io/platform-apps/mechanic:0.1.0-1
        imagePullPolicy: Always
        securityContext:
          privileged: true # Gives permission to nsenter /proc/1/ns/mnt
          readOnlyRootFilesystem: true
        env:
        - name: MECHANIC_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
