name: mechanic CI

on:
  push:
    branches:
      - master
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.goreleaser.yaml'
      - '.github/workflows/test-run.yaml'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.goreleaser.yaml'
      - '.github/workflows/test-run.yaml'

permissions:
  contents: read

jobs:
  test-run:
    if: github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
    - name: Install dependencies
      run: go mod download
    - name: Run tests
      run: go test -cover -v ./...
  goreleaser-build:
    if: github.event.pull_request.base.ref == 'master'
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        distribution: goreleaser
        version: "~> v2"
        args: build --snapshot --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}